x-superset-image: &superset-image unitel/superset-chrome:update-Lao

services:
  superset:
    image: *superset-image
    user: "root"
    container_name: superset_app
    command: [ "/app/docker/docker-bootstrap.sh", "app-gunicorn" ]
    env_file: .env
    environment:
      - SERVER_WORKER_AMOUNT=8
      - SERVER_THREADS_AMOUNT=10
      - GUNICORN_TIMEOUT=600
      - GUNICORN_KEEPALIVE=2
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
      - WEBDRIVER_TYPE=chrome
      - SCREENSHOT_SELENIUM_WEBDRIVER=chrome
    networks:
      - superset-net
    restart: unless-stopped
    ports:
      - 8088:8088
    volumes:
      - ./superset_config.py:/app/superset_config.py
      - ./superset/charts/data/api.py:/app/superset/charts/data/api.py
      - ./superset/charts/post_processing.py:/app/superset/charts/post_processing.py
      - ./superset/common/query_context_processor.py:/app/superset/common/query_context_processor.py
      - ./superset/utils/excel.py:/app/superset/utils/excel.py
      - ./superset/utils/filename_utils.py:/app/superset/utils/filename_utils.py
      - ./superset/reports/notifications/email.py:/app/superset/reports/notifications/email.py
      - ./superset/reports/notifications/base.py:/app/superset/reports/notifications/base.py
      - ./superset/commands/report/execute.py:/app/superset/commands/report/execute.py
      - ./superset/utils/csv.py:/app/superset/utils/csv.py
      - ./superset/static/assets:/app/superset/static/assets
      - ./docker/docker-bootstrap.sh:/app/docker/docker-bootstrap.sh
      - ./docker/requirements-local.txt:/app/docker/requirements-local.txt

  superset-db:
    image: postgres:15
    container_name: superset_db
    env_file: .env
    networks:
      - superset-net
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data

  superset-cache:
    image: redis:7
    container_name: superset_cache
    env_file: .env
    networks:
      - superset-net
    restart: unless-stopped
    volumes:
      - redis_home:/data

  superset-nginx:
    image: nginx:latest
    container_name: superset_nginx
    networks:
      - superset-net
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  superset-worker-beat:
    image: *superset-image
    user: "root"
    container_name: superset_worker_beat
    command: [ "/app/docker/docker-bootstrap.sh", "beat" ]
    env_file: .env
    environment:
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
      - WEBDRIVER_TYPE=chrome
      - SCREENSHOT_SELENIUM_WEBDRIVER=chrome
    networks:
      - superset-net
    restart: unless-stopped
    shm_size: 2g
    volumes:
      - ./superset_config.py:/app/superset_config.py
      - ./superset/charts/data/api.py:/app/superset/charts/data/api.py
      - ./superset/charts/post_processing.py:/app/superset/charts/post_processing.py
      - ./superset/common/query_context_processor.py:/app/superset/common/query_context_processor.py
      - ./superset/utils/excel.py:/app/superset/utils/excel.py
      - ./superset/utils/filename_utils.py:/app/superset/utils/filename_utils.py
      - ./superset/reports/notifications/email.py:/app/superset/reports/notifications/email.py
      - ./superset/reports/notifications/base.py:/app/superset/reports/notifications/base.py
      - ./superset/commands/report/execute.py:/app/superset/commands/report/execute.py
      - ./superset/utils/csv.py:/app/superset/utils/csv.py
      - ./superset/static/assets:/app/superset/static/assets
      - ./docker/docker-bootstrap.sh:/app/docker/docker-bootstrap.sh
      - ./docker/requirements-local.txt:/app/docker/requirements-local.txt
    healthcheck:
      disable: true

  superset-worker-reports:
    image: *superset-image
    user: "root"
    deploy:
      mode: replicated
      replicas: 3
    command: [ "/app/docker/docker-bootstrap.sh", "custom", "celery", "--app=superset.tasks.celery_app:app", "worker", "--pool=prefork", "-O", "fair", "-c", "4", "--queues=reports,default", "--loglevel=INFO" ]
    env_file: .env
    environment:
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
      - WEBDRIVER_TYPE=chrome
      - SCREENSHOT_SELENIUM_WEBDRIVER=chrome
    networks:
      - superset-net
    restart: unless-stopped
    shm_size: 2g
    volumes:
      - ./superset_config.py:/app/superset_config.py
      - ./superset/charts/data/api.py:/app/superset/charts/data/api.py
      - ./superset/charts/post_processing.py:/app/superset/charts/post_processing.py
      - ./superset/common/query_context_processor.py:/app/superset/common/query_context_processor.py
      - ./superset/utils/excel.py:/app/superset/utils/excel.py
      - ./superset/utils/filename_utils.py:/app/superset/utils/filename_utils.py
      - ./superset/reports/notifications/email.py:/app/superset/reports/notifications/email.py
      - ./superset/reports/notifications/base.py:/app/superset/reports/notifications/base.py
      - ./superset/commands/report/execute.py:/app/superset/commands/report/execute.py
      - ./superset/utils/csv.py:/app/superset/utils/csv.py
      - ./superset/static/assets:/app/superset/static/assets
      - ./docker/docker-bootstrap.sh:/app/docker/docker-bootstrap.sh
      - ./docker/requirements-local.txt:/app/docker/requirements-local.txt
    healthcheck:
      test: [ "CMD-SHELL", "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME" ]

  superset-worker-sqllab:
    image: *superset-image
    user: "root"
    container_name: superset_worker_sqllab
    command: [ "/app/docker/docker-bootstrap.sh", "custom", "celery", "--app=superset.tasks.celery_app:app", "worker", "--pool=prefork", "-O", "fair", "-c", "4", "--queues=sql_lab" ]
    env_file: .env
    environment:
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
      - WEBDRIVER_TYPE=chrome
      - SCREENSHOT_SELENIUM_WEBDRIVER=chrome
    networks:
      - superset-net
    restart: unless-stopped
    shm_size: 2g
    volumes:
      - ./superset_config.py:/app/superset_config.py
      - ./superset/charts/data/api.py:/app/superset/charts/data/api.py
      - ./superset/charts/post_processing.py:/app/superset/charts/post_processing.py
      - ./superset/common/query_context_processor.py:/app/superset/common/query_context_processor.py
      - ./superset/utils/excel.py:/app/superset/utils/excel.py
      - ./superset/utils/filename_utils.py:/app/superset/utils/filename_utils.py
      - ./superset/reports/notifications/email.py:/app/superset/reports/notifications/email.py
      - ./superset/reports/notifications/base.py:/app/superset/reports/notifications/base.py
      - ./superset/commands/report/execute.py:/app/superset/commands/report/execute.py
      - ./superset/utils/csv.py:/app/superset/utils/csv.py
      - ./superset/static/assets:/app/superset/static/assets
      - ./docker/docker-bootstrap.sh:/app/docker/docker-bootstrap.sh
      - ./docker/requirements-local.txt:/app/docker/requirements-local.txt
    healthcheck:
      test: [ "CMD-SHELL", "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME" ]

  superset-daily-restart:
    image: alpine:3.20
    container_name: superset_daily_restart
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -ce '
        apk add --no-cache curl dcron tzdata &&
        echo "15 6 * * * /usr/bin/curl --fail --silent --show-error --unix-socket /var/run/docker.sock -X POST http://localhost/containers/superset_app/restart" > /etc/crontabs/root &&
        crond -f -l 8
      '
    restart: unless-stopped
    networks:
      - superset-net

networks:
  superset-net:
    name: superset_net

volumes:
  db_home:
  redis_home:
